# Generated by Django 6.0.6 on 2026-06-10 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(db_column='idasistente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('tipo_asistente', models.CharField(choices=[('General', 'General'), ('Prensa', 'Prensa'), ('Industria', 'Industria'), ('VIP', 'VIP'), ('Jurado', 'Jurado')], db_column='tipoasistente', default='General', max_length=15)),
            ],
            options={
                'db_table': 'asistentes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idcategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombrecategoria', max_length=80)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(db_column='idpelicula', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=150)),
                ('anio_prod', models.IntegerField(db_column='anioprod', validators=[django.core.validators.MinValueValidator(1889)])),
                ('duracion', models.IntegerField(db_column='duracion', validators=[django.core.validators.MinValueValidator(1)])),
                ('pais_orig', models.CharField(db_column='paisorigen', max_length=60)),
                ('sinopsis', models.TextField(blank=True, db_column='sinopsis', null=True)),
                ('clasificacion', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('ATP', 'ATP')], db_column='clasificacion', max_length=10)),
                ('formato', models.CharField(choices=[('Digital', 'Digital'), ('35mm', '35mm'), ('IMAX', 'IMAX')], db_column='formato', max_length=10)),
                ('estado', models.CharField(choices=[('Postulada', 'Postulada'), ('Seleccionada', 'Seleccionada'), ('Rechazada', 'Rechazada'), ('Premiada', 'Premiada')], db_column='estado', default='Postulada', max_length=15)),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id_edicion', models.AutoField(db_column='idedicion', primary_key=True, serialize=False)),
                ('anio', models.IntegerField(db_column='anio', unique=True)),
                ('nombre_edicion', models.CharField(blank=True, db_column='nombreedicion', max_length=100, null=True)),
                ('fecha_inicio', models.DateField(db_column='fechainicio')),
                ('fecha_fin', models.DateField(db_column='fechafin')),
            ],
            options={
                'db_table': 'ediciones',
            },
        ),
        migrations.CreateModel(
            name='EventoParalelo',
            fields=[
                ('id_evento', models.AutoField(db_column='idevento', primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(db_column='nombreevento', max_length=150)),
                ('tipo_evento', models.CharField(choices=[('Masterclass', 'Masterclass'), ('Taller', 'Taller'), ('Coctel', 'Coctel')], db_column='tipoevento', max_length=15)),
                ('fecha_hora', models.DateTimeField(db_column='fechahora')),
                ('aforo', models.IntegerField(db_column='aforo', validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_inscripcion', models.DecimalField(db_column='costoinscripcion', decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
            ],
            options={
                'db_table': 'eventosparalelos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idgenero', primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(db_column='nombregenero', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(db_column='idhotel', primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(db_column='nombrehotel', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True)),
                ('estrellas', models.IntegerField(blank=True, db_column='estrellas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'hoteles',
            },
        ),
        migrations.CreateModel(
            name='MiembroJurado',
            fields=[
                ('id_miembro', models.AutoField(db_column='idmiembro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('profesion', models.CharField(blank=True, db_column='profesion', max_length=60, null=True)),
                ('pais', models.CharField(blank=True, db_column='pais', max_length=60, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'miembrosjurado',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id_patrocinador', models.AutoField(db_column='idpatrocinador', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='nombreempresa', max_length=100)),
                ('contacto', models.CharField(blank=True, db_column='contacto', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('redes_sociales', models.CharField(blank=True, db_column='redessociales', max_length=150, null=True)),
            ],
            options={
                'db_table': 'patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(db_column='idpersonal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('biografia', models.TextField(blank=True, db_column='biografia', null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, db_column='nacionalidad', max_length=60, null=True)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(db_column='idsala', primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(db_column='nombresala', max_length=60)),
                ('capacidad', models.IntegerField(db_column='capacidad', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(db_column='idsede', primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(db_column='nombresede', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=60, null=True)),
                ('sitio_web', models.CharField(blank=True, db_column='sitioweb', max_length=100, null=True)),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(db_column='idtarifa', primary_key=True, serialize=False)),
                ('nombre_tarifa', models.CharField(db_column='nombretarifa', max_length=30)),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'tarifas',
            },
        ),
        migrations.CreateModel(
            name='TipoAbono',
            fields=[
                ('id_tipo_abono', models.AutoField(db_column='idtipoabono', primary_key=True, serialize=False)),
                ('nombre_abono', models.CharField(db_column='nombreabono', max_length=60)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'tiposabono',
            },
        ),
        migrations.CreateModel(
            name='JuradoCategoria',
            fields=[
                ('miembro', models.ForeignKey(db_column='idmiembro', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.miembrojurado')),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'db_table': 'juradocategoria',
                'unique_together': {('miembro', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='PatrocinioEdicion',
            fields=[
                ('id_patrocinio', models.AutoField(db_column='idpatrocinio', primary_key=True, serialize=False)),
                ('tipo_aporte', models.CharField(choices=[('Economico', 'Economico'), ('Especie', 'Especie')], db_column='tipoaporte', max_length=10)),
                ('monto', models.DecimalField(blank=True, db_column='monto', decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_aporte', models.CharField(blank=True, db_column='descripcionaporte', max_length=200, null=True)),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('patrocinador', models.ForeignKey(db_column='idpatrocinador', on_delete=django.db.models.deletion.CASCADE, to='api.patrocinador')),
            ],
            options={
                'db_table': 'patrocinioedicion',
            },
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id_alojamiento', models.AutoField(db_column='idalojamiento', primary_key=True, serialize=False)),
                ('nro_habitacion', models.CharField(db_column='nrohabitacion', max_length=10)),
                ('check_in', models.DateField(db_column='checkin')),
                ('check_out', models.DateField(db_column='checkout')),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('hotel', models.ForeignKey(db_column='idhotel', on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('personal', models.ForeignKey(db_column='idpersonal', on_delete=django.db.models.deletion.CASCADE, to='api.personal')),
            ],
            options={
                'db_table': 'alojamientos',
            },
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id_proyeccion', models.AutoField(db_column='idproyeccion', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='fechahora')),
                ('tiene_qa', models.BooleanField(db_column='tieneqa', default=False)),
                ('aforo_disponible', models.IntegerField(db_column='aforodisponible', validators=[django.core.validators.MinValueValidator(0)])),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('sala', models.ForeignKey(db_column='idsala', on_delete=django.db.models.deletion.CASCADE, to='api.sala')),
            ],
            options={
                'db_table': 'proyecciones',
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='sede',
            field=models.ForeignKey(db_column='idsede', on_delete=django.db.models.deletion.CASCADE, to='api.sede'),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id_traslado', models.AutoField(db_column='idtraslado', primary_key=True, serialize=False)),
                ('tipo_traslado', models.CharField(choices=[('Vuelo', 'Vuelo'), ('Transfer', 'Transfer')], db_column='tipotraslado', max_length=10)),
                ('origen', models.CharField(db_column='origen', max_length=100)),
                ('destino', models.CharField(db_column='destino', max_length=100)),
                ('fecha_hora', models.DateTimeField(db_column='fechahora')),
                ('nro_vuelo', models.CharField(blank=True, db_column='nrovuelo', max_length=20, null=True)),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('personal', models.ForeignKey(db_column='idpersonal', on_delete=django.db.models.deletion.CASCADE, to='api.personal')),
            ],
            options={
                'db_table': 'traslados',
            },
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pelicula')),
                ('genero', models.ForeignKey(db_column='idgenero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'peliculagenero',
                'unique_together': {('pelicula', 'genero')},
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(related_name='peliculas', through='api.PeliculaGenero', to='api.genero'),
        ),
        migrations.CreateModel(
            name='ExpositorEvento',
            fields=[
                ('evento', models.ForeignKey(db_column='idevento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.eventoparalelo')),
                ('personal', models.ForeignKey(db_column='idpersonal', on_delete=django.db.models.deletion.CASCADE, to='api.personal')),
            ],
            options={
                'db_table': 'expositorevento',
                'unique_together': {('evento', 'personal')},
            },
        ),
        migrations.AddField(
            model_name='eventoparalelo',
            name='expositores',
            field=models.ManyToManyField(related_name='eventos_paralelos', through='api.ExpositorEvento', to='api.personal'),
        ),
        migrations.AddField(
            model_name='miembrojurado',
            name='categorias',
            field=models.ManyToManyField(related_name='jurados', through='api.JuradoCategoria', to='api.categoria'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(db_column='idevaluacion', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(db_column='puntuacion', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, db_column='comentario', null=True)),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
                ('miembro', models.ForeignKey(db_column='idmiembro', on_delete=django.db.models.deletion.CASCADE, to='api.miembrojurado')),
            ],
            options={
                'db_table': 'evaluaciones',
                'unique_together': {('miembro', 'pelicula', 'categoria', 'edicion')},
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id_premio', models.AutoField(db_column='idpremio', primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
            ],
            options={
                'db_table': 'premios',
                'unique_together': {('categoria', 'edicion')},
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_entrada', models.AutoField(db_column='identrada', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, db_column='fechacompra')),
                ('asistente', models.ForeignKey(db_column='idasistente', on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
                ('evento', models.ForeignKey(blank=True, db_column='idevento', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.eventoparalelo')),
                ('proyeccion', models.ForeignKey(blank=True, db_column='idproyeccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proyeccion')),
                ('tarifa', models.ForeignKey(db_column='idtarifa', on_delete=django.db.models.deletion.CASCADE, to='api.tarifa')),
            ],
            options={
                'db_table': 'entradas',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('evento__isnull', True), ('proyeccion__isnull', False)), models.Q(('evento__isnull', False), ('proyeccion__isnull', True)), _connector='OR'), name='ck_ent_destino'), models.UniqueConstraint(condition=models.Q(('proyeccion__isnull', False)), fields=('asistente', 'proyeccion'), name='ux_ent_asiproy'), models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('asistente', 'evento'), name='ux_ent_asievt')],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.AutoField(db_column='idabono', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, db_column='fechacompra')),
                ('codigo_acceso', models.CharField(db_column='codigoacceso', max_length=20, unique=True)),
                ('pagado', models.BooleanField(db_column='pagado', default=False)),
                ('asistente', models.ForeignKey(db_column='idasistente', on_delete=django.db.models.deletion.CASCADE, to='api.asistente')),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
                ('tipo_abono', models.ForeignKey(db_column='idtipoabono', on_delete=django.db.models.deletion.CASCADE, to='api.tipoabono')),
            ],
            options={
                'db_table': 'abonos',
                'unique_together': {('asistente', 'tipo_abono')},
            },
        ),
        migrations.CreateModel(
            name='CompetenciaPelicula',
            fields=[
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pelicula')),
                ('categoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('edicion', models.ForeignKey(db_column='idedicion', on_delete=django.db.models.deletion.CASCADE, to='api.edicion')),
            ],
            options={
                'db_table': 'competenciapelicula',
                'unique_together': {('pelicula', 'categoria', 'edicion')},
            },
        ),
        migrations.CreateModel(
            name='RolPelicula',
            fields=[
                ('personal', models.ForeignKey(db_column='idpersonal', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.personal')),
                ('rol', models.CharField(choices=[('Director', 'Director'), ('Actor', 'Actor'), ('Guionista', 'Guionista'), ('Productor', 'Productor')], db_column='rol', max_length=20)),
                ('pelicula', models.ForeignKey(db_column='idpelicula', on_delete=django.db.models.deletion.CASCADE, to='api.pelicula')),
            ],
            options={
                'db_table': 'rolespelicula',
                'unique_together': {('personal', 'pelicula', 'rol')},
            },
        ),
    ]
